[project]
site_name = "Notebook"
site_description = "Public notebook"
site_author = "Shujie Gao"
site_url = "https://note.shujie.cc/"
repo_url = "https://github.com/gsjz/notebook"
repo_name = "gsjz/notebook"
docs_dir = "docs"
site_dir = "site-public"
extra_css = ["stylesheets/no-footer.css", "stylesheets/callouts.css", "stylesheets/distribution-explorer.css", "stylesheets/image-viewer.css"]
extra_javascript = ["javascripts/katex.js", "javascripts/hot-reload-state.js", "javascripts/image-viewer.js"]
nav = [
    { "首页" = "index.md" },
    { "CS" = "public/cs"},
    { "AI" = "public/ai"},
    { "Math" = "public/math"},
    { "Eng" = "public/eng"},
    { "XCPC" = "public/xcpc" },
    { "ZZ" = "public/zz" },
]

[project.extra]
generator = false

[project.theme]
language = "zh"
favicon = "assets/images/site-logo.svg"
logo = "assets/images/site-logo.svg"

features = [
    "content.code.annotate",
    "content.code.copy",
    "navigation.indexes",
    "navigation.instant",
    "navigation.top",
]

[project.theme.font]
text = "Inter"
code = "Jetbrains Mono"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
