[project]
site_name = "Notebook"
site_description = "Public notebook"
site_author = "Shujie Gao"
site_url = "https://note.shujie.cc/"
repo_url = "https://github.com/gsjz/notebook"
repo_name = "gsjz/notebook"
docs_dir = "docs"
site_dir = "site-public"
extra_css = ["stylesheets/no-footer.css", "stylesheets/callouts.css", "stylesheets/distribution-explorer.css", "stylesheets/image-viewer.css"]
extra_javascript = ["javascripts/katex.js", "javascripts/hot-reload-state.js", "javascripts/image-viewer.js"]
nav = [
    { "首页" = "index.md" },
    { "CS" = "public/cs/"},
    { "AI" = "public/ai/"},
    { "Math" = "public/math/"},
    { "Eng" = "public/eng/"},
    { "ZZ" = "public/zz/" },
]

[project.markdown_extensions]
"notebook_mdx.list_continuation" = {}
abbr = {}
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
toc = { permalink = true }

[project.markdown_extensions.pymdownx]
arithmatex = { generic = true }
betterem = {}
caret = {}
details = {}
emoji = { emoji_generator = "zensical.extensions.emoji.to_svg", emoji_index = "zensical.extensions.emoji.twemoji" }
highlight = { anchor_linenums = true, line_spans = "__span", pygments_lang_class = true }
inlinehilite = {}
keys = {}
magiclink = {}
mark = {}
smartsymbols = {}
superfences = { custom_fences = [{ name = "mermaid", class = "mermaid" }] }
tabbed = { alternate_style = true, combine_header_slug = true }
tasklist = { custom_checkbox = true }
tilde = {}

[project.extra]
generator = false

[project.theme]
language = "zh"
favicon = "assets/images/site-logo.svg"
logo = "assets/images/site-logo.svg"

features = [
    "content.code.annotate",
    "content.code.copy",
    "navigation.indexes",
    "navigation.instant",
    "navigation.top",
]

[project.theme.font]
text = "Inter"
code = "Jetbrains Mono"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
